python GraphRank.py --seed 0 --dataset_name citeseer --model_name gat
python GraphRank.py --seed 0 --dataset_name citeseer --model_name gcn
python GraphRank.py --seed 0 --dataset_name citeseer --model_name graphsage
python GraphRank.py --seed 0 --dataset_name citeseer --model_name tagcn
python GraphRank.py --seed 0 --dataset_name cora --model_name gat
python GraphRank.py --seed 0 --dataset_name cora --model_name gcn
python GraphRank.py --seed 0 --dataset_name cora --model_name graphsage
python GraphRank.py --seed 0 --dataset_name cora --model_name tagcn
python GraphRank.py --seed 0 --dataset_name pubmed --model_name gat
python GraphRank.py --seed 0 --dataset_name pubmed --model_name gcn
python GraphRank.py --seed 0 --dataset_name pubmed --model_name graphsage
python GraphRank.py --seed 0 --dataset_name pubmed --model_name tagcn
python GraphRank.py --seed 0 --dataset_name coauthorcs --model_name gat
python GraphRank.py --seed 0 --dataset_name coauthorcs --model_name gcn
python GraphRank.py --seed 0 --dataset_name coauthorcs --model_name graphsage
python GraphRank.py --seed 0 --dataset_name coauthorcs --model_name tagcn
python GraphRank.py --seed 1 --dataset_name citeseer --model_name gat
python GraphRank.py --seed 1 --dataset_name citeseer --model_name gcn
python GraphRank.py --seed 1 --dataset_name citeseer --model_name graphsage
python GraphRank.py --seed 1 --dataset_name citeseer --model_name tagcn
python GraphRank.py --seed 1 --dataset_name cora --model_name gat
python GraphRank.py --seed 1 --dataset_name cora --model_name gcn
python GraphRank.py --seed 1 --dataset_name cora --model_name graphsage
python GraphRank.py --seed 1 --dataset_name cora --model_name tagcn
python GraphRank.py --seed 1 --dataset_name pubmed --model_name gat
python GraphRank.py --seed 1 --dataset_name pubmed --model_name gcn
python GraphRank.py --seed 1 --dataset_name pubmed --model_name graphsage
python GraphRank.py --seed 1 --dataset_name pubmed --model_name tagcn
python GraphRank.py --seed 1 --dataset_name coauthorcs --model_name gat
python GraphRank.py --seed 1 --dataset_name coauthorcs --model_name gcn
python GraphRank.py --seed 1 --dataset_name coauthorcs --model_name graphsage
python GraphRank.py --seed 1 --dataset_name coauthorcs --model_name tagcn
python GraphRank.py --seed 2 --dataset_name citeseer --model_name gat
python GraphRank.py --seed 2 --dataset_name citeseer --model_name gcn
python GraphRank.py --seed 2 --dataset_name citeseer --model_name graphsage
python GraphRank.py --seed 2 --dataset_name citeseer --model_name tagcn
python GraphRank.py --seed 2 --dataset_name cora --model_name gat
python GraphRank.py --seed 2 --dataset_name cora --model_name gcn
python GraphRank.py --seed 2 --dataset_name cora --model_name graphsage
python GraphRank.py --seed 2 --dataset_name cora --model_name tagcn
python GraphRank.py --seed 2 --dataset_name pubmed --model_name gat
python GraphRank.py --seed 2 --dataset_name pubmed --model_name gcn
python GraphRank.py --seed 2 --dataset_name pubmed --model_name graphsage
python GraphRank.py --seed 2 --dataset_name pubmed --model_name tagcn
python GraphRank.py --seed 2 --dataset_name coauthorcs --model_name gat
python GraphRank.py --seed 2 --dataset_name coauthorcs --model_name gcn
python GraphRank.py --seed 2 --dataset_name coauthorcs --model_name graphsage
python GraphRank.py --seed 2 --dataset_name coauthorcs --model_name tagcn
python GraphRank.py --seed 3 --dataset_name citeseer --model_name gat
python GraphRank.py --seed 3 --dataset_name citeseer --model_name gcn
python GraphRank.py --seed 3 --dataset_name citeseer --model_name graphsage
python GraphRank.py --seed 3 --dataset_name citeseer --model_name tagcn
python GraphRank.py --seed 3 --dataset_name cora --model_name gat
python GraphRank.py --seed 3 --dataset_name cora --model_name gcn
python GraphRank.py --seed 3 --dataset_name cora --model_name graphsage
python GraphRank.py --seed 3 --dataset_name cora --model_name tagcn
python GraphRank.py --seed 3 --dataset_name pubmed --model_name gat
python GraphRank.py --seed 3 --dataset_name pubmed --model_name gcn
python GraphRank.py --seed 3 --dataset_name pubmed --model_name graphsage
python GraphRank.py --seed 3 --dataset_name pubmed --model_name tagcn
python GraphRank.py --seed 3 --dataset_name coauthorcs --model_name gat
python GraphRank.py --seed 3 --dataset_name coauthorcs --model_name gcn
python GraphRank.py --seed 3 --dataset_name coauthorcs --model_name graphsage
python GraphRank.py --seed 3 --dataset_name coauthorcs --model_name tagcn
python GraphRank.py --seed 4 --dataset_name citeseer --model_name gat
python GraphRank.py --seed 4 --dataset_name citeseer --model_name gcn
python GraphRank.py --seed 4 --dataset_name citeseer --model_name graphsage
python GraphRank.py --seed 4 --dataset_name citeseer --model_name tagcn
python GraphRank.py --seed 4 --dataset_name cora --model_name gat
python GraphRank.py --seed 4 --dataset_name cora --model_name gcn
python GraphRank.py --seed 4 --dataset_name cora --model_name graphsage
python GraphRank.py --seed 4 --dataset_name cora --model_name tagcn
python GraphRank.py --seed 4 --dataset_name pubmed --model_name gat
python GraphRank.py --seed 4 --dataset_name pubmed --model_name gcn
python GraphRank.py --seed 4 --dataset_name pubmed --model_name graphsage
python GraphRank.py --seed 4 --dataset_name pubmed --model_name tagcn
python GraphRank.py --seed 4 --dataset_name coauthorcs --model_name gat
python GraphRank.py --seed 4 --dataset_name coauthorcs --model_name gcn
python GraphRank.py --seed 4 --dataset_name coauthorcs --model_name graphsage
python GraphRank.py --seed 4 --dataset_name coauthorcs --model_name tagcn
