python deterministic.py --seed 0
python deterministic.py --seed 1
python deterministic.py --seed 2
python deterministic.py --seed 3
python deterministic.py --seed 4
python deterministic.py --seed 5
python deterministic.py --seed 6
python deterministic.py --seed 7
python deterministic.py --seed 8
python deterministic.py --seed 9