python mlp.py --seed 0 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 0 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 0 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 0 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 1 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 1 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 1 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 1 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 2 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 2 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 2 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 2 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 3 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 3 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 3 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 3 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 4 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 4 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 4 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 4 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 5 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 5 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 5 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 5 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 6 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 6 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 6 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 6 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 7 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 7 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 7 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 7 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 8 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 8 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 8 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 8 --dataset_name coauthorcs --model_name tagcn
python mlp.py --seed 9 --dataset_name coauthorcs --model_name gat
python mlp.py --seed 9 --dataset_name coauthorcs --model_name gcn
python mlp.py --seed 9 --dataset_name coauthorcs --model_name graphsage
python mlp.py --seed 9 --dataset_name coauthorcs --model_name tagcn
