python get_mutation_models.py --seed 0 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 0 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 0 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 0 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 0 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 0 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 0 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 0 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 0 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 0 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 0 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 0 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 0 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 0 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 0 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 0 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 1 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 1 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 1 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 1 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 1 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 1 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 1 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 1 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 1 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 1 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 1 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 1 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 1 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 1 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 1 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 1 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 2 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 2 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 2 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 2 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 2 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 2 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 2 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 2 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 2 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 2 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 2 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 2 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 2 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 2 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 2 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 2 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 3 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 3 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 3 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 3 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 3 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 3 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 3 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 3 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 3 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 3 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 3 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 3 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 3 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 3 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 3 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 3 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 4 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 4 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 4 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 4 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 4 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 4 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 4 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 4 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 4 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 4 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 4 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 4 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 4 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 4 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 4 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 4 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 5 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 5 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 5 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 5 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 5 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 5 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 5 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 5 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 5 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 5 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 5 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 5 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 5 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 5 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 5 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 5 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 6 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 6 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 6 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 6 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 6 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 6 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 6 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 6 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 6 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 6 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 6 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 6 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 6 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 6 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 6 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 6 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 7 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 7 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 7 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 7 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 7 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 7 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 7 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 7 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 7 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 7 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 7 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 7 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 7 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 7 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 7 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 7 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 8 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 8 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 8 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 8 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 8 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 8 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 8 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 8 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 8 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 8 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 8 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 8 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 8 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 8 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 8 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 8 --dataset_name coauthorcs --model_name tagcn
python get_mutation_models.py --seed 9 --dataset_name citeseer --model_name gat
python get_mutation_models.py --seed 9 --dataset_name citeseer --model_name gcn
python get_mutation_models.py --seed 9 --dataset_name citeseer --model_name graphsage
python get_mutation_models.py --seed 9 --dataset_name citeseer --model_name tagcn
python get_mutation_models.py --seed 9 --dataset_name cora --model_name gat
python get_mutation_models.py --seed 9 --dataset_name cora --model_name gcn
python get_mutation_models.py --seed 9 --dataset_name cora --model_name graphsage
python get_mutation_models.py --seed 9 --dataset_name cora --model_name tagcn
python get_mutation_models.py --seed 9 --dataset_name pubmed --model_name gat
python get_mutation_models.py --seed 9 --dataset_name pubmed --model_name gcn
python get_mutation_models.py --seed 9 --dataset_name pubmed --model_name graphsage
python get_mutation_models.py --seed 9 --dataset_name pubmed --model_name tagcn
python get_mutation_models.py --seed 9 --dataset_name coauthorcs --model_name gat
python get_mutation_models.py --seed 9 --dataset_name coauthorcs --model_name gcn
python get_mutation_models.py --seed 9 --dataset_name coauthorcs --model_name graphsage
python get_mutation_models.py --seed 9 --dataset_name coauthorcs --model_name tagcn
